# Generated by Django 3.0.8 on 2020-08-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200805_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
